-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Mar 25, 2022 at 09:03 PM
-- Server version: 10.4.22-MariaDB
-- PHP Version: 8.0.13

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `xmen_database`
--

-- --------------------------------------------------------

--
-- Table structure for table `xmen_heroes`
--

CREATE TABLE `xmen_heroes` (
  `hero_id` int(11) NOT NULL,
  `hero_name` varchar(1000) NOT NULL,
  `hero_image` varchar(255) NOT NULL,
  `hero_real_name` varchar(255) NOT NULL,
  `hero_short_bio` varchar(1000) NOT NULL,
  `hero_long_bio` varchar(1000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `xmen_heroes`
--

INSERT INTO `xmen_heroes` (`hero_id`, `hero_name`, `hero_image`, `hero_real_name`, `hero_short_bio`, `hero_long_bio`) VALUES
(1, 'Professor X', 'professor x.jpg', 'Charles Xavier', 'Charles Xavier is the founder of the X-Men and was the original headmaster of the Xavier Institute of Higher Learning.\r\n\r\nJoins In : The X-Men, vol. 1 #42 (1968, flasback)\r\n\r\nLast Seen : Avengers Vs. X-Men #11 (Currently deceased)', 'Professor Charles Xavier is the creator of the X-Men and founder of the Xavier School for Gifted Youngsters. His dream of peaceful coexistence between mutants and humanity has long been the driving force for the X-Men. An immensely powerful telepath and scientific genius, Xavier was among the world\'s greatest masterminds. Killed at the hands of a Phoenix crazed Cyclops, Xavier\'s memory and dream still remains and motivates his X-Men to keep fighting for a world that fears and hates them.'),
(2, 'Cyclops', 'Cyclops.jpg', 'Scott Summers', 'Scott Summers was Xavier\'s first recruit and often the group\'s field leader. Former headmaster of the Xavier Institute, former leader of the X-Factor, and current leader of the Uncanny X-Men.  Joins In : The X-men, vol.1 #42 (1968, flashback)  Last Seen : All New X-Men and Uncanny X-Men (ongoing series)', 'The first X-Man, Scott Summers possesses the mutant ability to fire powerful concussive blasts through his eyes that act as a portal to another dimension full of the force that makes up his optic blast. He is visually distinctive for the ruby quartz visor he wears to control his devastating power. A born leader, Cyclops succeeded his mentor Professor X to command the X-Men.'),
(3, 'Angel', 'Angel.jpg', 'Warren Worthington', 'Warren Worthington III is the third official member of the original team, he is the only one to have acted as a costumed superheroes before joining the X-Men. Former member of the Champions, The Defenders, X-Factor and X-Force.  Joins In : The X-Men, vol. 1 #56 (1969, flashback)  Last Seen : Wolverine and the X-Men (ongoing series)', 'A mutant and original member of the X-Men, Warren received his angelic wings at a young age along with a unique healing factor in his blood. After being twisted into a weapon of Apocalypse, Warren became the cold and distant Archangel. In the years since then, he\'s gone back and forth between his two identities.'),
(4, 'Beast', 'Beast.jpg', 'Dr. Henry \"Hank\" McCoy', 'Dr. Henry \"Hank\" McCoy was the original team\'s scientist. Former member of the Avengers, the Defenders and X-Factor. Currently, he is the vice principal of the Jean Grey School for Higher Learning, he is also an agent of S.W.O.R.D and the Illuminati.  Joins In : The X-Men, vol 1. #53 (1969, flashback)  Last Seen : Amazing X-Men and New Avengers (ongoing series)', 'A founding member of the X-Men, Dr. Hank McCoy is a mutant possessing animal-like strength and agility. Despite being covered in blue fur and resembling a ferocious beast, Hank possesses an astounding intellect and a superb wit. He is currently a key member of X-Force. Beast was created by the team of Stan Lee and Jack Kirby for the first X-Men book and thus first appeared in The (Uncanny) X-Men issue 1(1963).Beast originally started out as a man with larger appendages and a keen intellect. He would undergo two changes in appearance: the first was into a man with blue fur and claws; the second was a further mutation into a more feline-looking animal with the same type of blue fur he previously had. He would maintain his intellect throughout each change.'),
(5, 'Jean Grey', 'Jean grey.jpeg', 'Jean Grey-Summers', 'Jean Grey-Summers is the fifth and final member to joins the original X-Men team, although she has met Xavier before the others. An avatar to the Phoenix Force, Jean Grey was one of the X-Men most powerful member as well as their most dangerous foes.  Joins In : The X-Men, vol 1 #1 (1963)  Last Seen : Avengers Vs. X-Men (2012)(Cameo)', 'Jean Grey was one of the five original X-Men. An omega-level mutant telepath and powerful telekinetic, Jean has gained near limitless powers as a recurrent host of the Phoenix Force. She is known for her return from death and as the wife of Cyclops. Jean Grey was created by Stan Lee and Jack Kirby, first appearing under the code name Marvel Girl in X-Men #1 in 1963. Jean was the first and (initially) only female member of the team, and was a regular part of the team during this run of publication. She began as a character whose sole ability was telekinesis. Years later, writers decided to give her telepathy. The writers explained that this was a suppressed ability that remained dormant (thanks to Xavier\'s intervention) while she was a teenager.'),
(6, 'Night Crawler', 'Night crawler.jpeg', 'Kurt Wagner', 'Kurt Wagner is the son of Mystique. A faithful Catholic, Kurt is one of the most beloved member of the X-Men. Former leader of Excalibur. He was killed in an attempt to save Hope Summers but later resurrected.  Joins In : Giant-Size X-Men #1 (1975)  Last Seen : Amazing X-Men and Nigthcrawler (ongoing series)', 'Kurt Wagner is a prominent member of the X-Men and former member and leader of Excalibur. He possessed the Neyaphemian ability of teleportation, as well as incredible agility, wall scaling and a prehensile tail. Nightcrawler is a devout Catholic, contrasting his demonic appearance. He is a highly skilled swordsmen and former circus acrobat. Nightcrawler was created by writer Len Wein and artist Dave Cockrum.Cockrum was working for DC comics at the time of his conception, he was originally supposed to be a demon from hell that failed a mission and was banished. He was to be a member of the Legion of Super Heroes. He made his debut in Giant Size X-Men #1 in 1975'),
(7, 'Wolverine', 'Wolverine.jpg', 'James Howlett (Logan)', 'James Howlett, better known as Logan, is arguably the most iconic member of the team. Formerm member of the U.S Army, Team X, Alpha Flight, Department H, Department K, the Defenders, the X-Men, and the Avengers. Former headmaster of the Jean Grey School for Higher Learning.  Joins In : Giant-Size X-Men #1 (1975)  Last Seen : Death of Wolverine vol. 1 (currently deceased)', 'A long-lived mutant with the rage of a beast and the soul of a Samurai, James \"Logan\" Howlett\'s once mysterious past is filled with blood, war, and betrayal. Possessing an accelerated healing factor, keenly enhanced senses, and bone claws in each hand (along with his skeleton) that are coated in adamantium; Wolverine is, without question, the ultimate weapon. Wolverine was created by Roy Thomas, Len Wein and John Romita, Sr.. Although Herb Trimpe drew the issues Wolverine first appeared in (a cameo on the last page) in The Incredible Hulk issue 180 (1974) and first fully appeared in The Incredible Hulk Vol. 1 issue 181 (1974), he is not acknowledged as an \"official\" co-creator from Marvel. At the time of his creation, comics were becoming increasingly popular in Canada and Roy Thomas, Marvel\'s then Editor-in-Chief, suggested to Len Wein to create a Canadian character to put in the Hulk comic he was working on called Wolverine. '),
(8, 'Storm', 'Storm.jpg', 'Ororo Monroe', 'Ororo Monroe, long considered as the second field leader of the X-Men. She has been the longest serving X-Men more than any other. Formerly maried to the Black Panther, she was also a former member of the Fantastic Four. Currently, she is the headmistress of the Jean Grey School for Higher Learning.  Joins In : Giant-Size X-Men #1 (1975)  Last Seen : Wolverine and The X-Men, Amazing X-Men, and X-Men (ongoing series)', 'An omega Level Mutant and Wakandan goddess, Ororo Munroe was born with the mutant ability to manipulate the elements and energies that make up the weather of any environment, including those present within living beings and the depths of space. Given the codename Storm, she is one of the most powerful mutants to walk the planet. Storm was created by the writer Len Wein and artist Dave Cockrum and made her first ever appearance in Giant Size X-Men # 1 in May 1975. Storm was created using different characters that were originally intended to be used in the Legion Of Superheroes comic book.'),
(9, 'Sunfire', 'Sunfire.jpeg', 'Shiro Yoshida', 'Shiro Yoshida actuallu quits the X-Men after only one mission, but keeps close relation with the team and proves to be a precious ally. He is depowered in New Avengers (2006), but regainded his powers when he turned into one of Apocalypse Horsemen.  Joins In : Giant-Size X-Men #1 (1975)  Last Seen : Uncanny Avengers (ongoing series)', 'Sunfire is a Japan mutant who converts solar radiation into plasma. After getting possessed by Apocalypse, he was stripped of his glory . He later served as a member in Uncanny Avengers. Shiro Yoshida grew up with a huge resentment against the United States. His mother was exposed to the radiation of the atomic bomb at Hiroshima and she died during his birth. His dad, a member of the Japanese Clan Yashida, became a diplomat to the United Nations and Shiro was pretty much raised by his uncle.  Shiro\'s uncle Tomo took him to a site in Hiroshima, and got him to touch the ground. There, the radioactive soil somehow triggered his mutation. Shiro trained for months before he was able to control his flame fully. His uncle Tomo was purely anti-America. He instilled his hatred upon Shiro and is responsible for giving him his costume and codename of Sunfire.'),
(10, 'Colossus', 'Colosses.jpeg', 'Piotr \"Peter\" Rasputin', 'Piotr \"Peter\" Rasputin is the brother of Magik, and longtime romantic interest of Kitty Pryde. Former member of Acolytes and Excalibur. He dies while releasing a cure for the Legacy Virus, but later resurrected by the Orb.  Joins In : Giant-Size X-Men #1 (1975)  Last Seen : Amazing X-Men (ongoing series)', 'Piotr Rasputin is a Russian mutant who possesses the ability to transform his body into organic steel, giving him immense strength and durability. Colossus is among the physically strongest X-Men, and is a talented artist. Piotr Nicolaevich Rasputin grew up on his family\'s farm in Russia. Piotr, his older brother Mikhail Rasputin, and younger sister Illyana Rasputin were all mutants. Piotr\'s ability to transform his body into organic steel allowed him to work around the farm and help out neighbors with ease. The Rasputin family was not related in any way to the fraudulent \"Man Of God\" Grigori Efimovich Rasputin, who became one of the court favorites of Tsar Nicolai II through taking advantage of Tsarevich Alexei Nicolaevich Romanov\'s hemophilia though years after being recruited by Professor X, Mr. Sinister would seek to draw doubt upon this relation in the story arch entitled X-Men: Colossus Bloodline.'),
(11, 'Magneto', 'Magneto.jpg', 'Max Eisenhardt', 'Max Eisenhardt is the longest serving enemies of the X-Men. He later joins the X-Men after seemingly \"redeemed\" himself and being appointed leader of the X-Men and the New Mutants. Once served as the headmaster of the Xavier Institute. He is the long time friend of Charles Xavier.  Joins In : Uncanny X-Men #200 (1985)  Last Seen : Magneto and Uncanny X-Men (ongoing series)', 'Among the most powerful, recognizable, and infamous mutants to inhabit the planet Earth, Magneto was the X-Men\'s first major nemesis. Now known as a revolutionist and terrorist, Magneto has fought for the X-Men as many times as he’s been against them. Magneto was created by writer Stan Lee and artist Jack Kirby in 1963. He made his first appearance in X-Men #1, becoming the very first foe of the iconic mutant team. Creator Stan Lee stated that he \"did not think of Magneto as a bad guy. He was just trying to strike back at the people who were so bigoted and racist. He was trying to defend mutants, and because society was not treating them fairly, he decided to teach society a lesson. He was a danger of course, but I never thought of him as a villain.\" Lee also explained that he originally planned for Magneto to be Professor Xavier\'s brother rather than simply an old friend.'),
(12, 'Cable', 'Cable.jpg', 'Nathan Summers', 'Nathan Summers is the son of Cyclops and Madelyne Pryor who was sent to the future as a baby and returned as an adult. He is the former mentor of the New Mutants and former member of the original X-Force. He is the adoptive father of Hope Summers. Currently, he lead his own X-Force team.  Joins In : Uncanny X-Men #381 (2000)  Last Seen : X-Force (ongoing series)', 'The once-mysterious Cable (a.k.a. Nathan Summers) is Cyclops\' time-traveling son who was infected with the deadly techno-organic virus during his infancy, which he keeps at bay using his advanced psionic powers. At one time a founding member and leader of the militant team called X-Force, previously known as the New Mutants, Cable takes the aimless youths under his wing and whips them into fighting shape in order to prepare them for future threats. The character of Cable was created by Rob Liefeld and was mostly framed by writers Louise Simonson and Fabian Nicieza who patterned the character after Liefeld\'s plots. It wasn\'t until much later that Nathan Christopher Charles Summers, infant son of Cyclops and the mercenary time-traveler from the future, were linked as being the same individual.'),
(13, 'Mystique', 'Mystique.jpg', '', 'One of X-Men greatest foes, Mystique was accepted as a probationary member of the X-Men. She was a former leader of the Brotherhood of Evil Mutans, she was also the foster mother of Rogue and the biological mother to Nightcrawler. Later she defected to the Marauders, whom she later betrayed as well.\r\n\r\nJoins In : X-Men, vol. 2 #181 (2006)\r\n\r\nLast Seen : Uncanny X-Men', 'True to her name, the shape shifting Mystique is an enigma. Is she a mutant terrorist determined to bring about the end of humanity, or a misguided mutant with a good heart? Mystique\'s first appearance was in Ms. Marvel #16 where she was seen in a shape-shifted form. She was first seen as Mystique two issues later. Both drawn by Jim Mooney (Dave Cockrum, however, designed the initial look of the character, so is also credited). Writer Chris Claremont stated that he originally planned to have Mystique and Destiny be Nightcrawler\'s biological parents, but due to the Comics Code Authority, Marvel refused to do this. However, years later Mystique and Destiny were confirmed to be a lesbian couple.'),
(14, 'Legion', 'Legion.jpg', 'David Haller', 'David Haller is the son of Professor X. He develops a multiple personality disorder due to trauma. He started the Age of Apocalypse. He erases himself from the existence after reaching the full extent of his power.  Joins In : X-Men: Legacy #250 (2011)  Last Seen : X-Men: Legacy, vol. 2, #24 (deceased, erased from existence)', 'The son of Charles Xavier and Gabrielle Haller, David Haller is the powerful Omega-level mutant known as Legion. He possesses hundreds of mutant abilities ranging from telekinesis to reality warping, but each power is controlled by a different persona, which could be either benevolent or malevolent. Legion was created by Chris Claremont and Bill Sienkiewicz and first appeared in a cameo in New Mutants issue 25 (1985) where a photo of him was seen and his character was discussed on paper by Professor Xavier. He first fully appeared in comics one issue later in The New Mutants issue 26 (1985).'),
(15, 'Deadpool', 'Deadpool.jpg', 'Wade Wilson', 'Wade Wilson regarded himself as a member of the X-Men. He is not mutant, rather gained his super healing factor from the DNA of Wolverine during the Weapon X process. He later visited Utopia and became a probationary member under the supervision from Domino. He went on to betray them, but still considers himself as an ally to the X-Men.  Join In : Cable & Deadpool #8 (2004)(probationary)  Last Seen : Deadpool and Thunderbolts', 'Wade Wilson is a former test subject of the Weapon X program, where he received his regenerative healing factor through the scientific experiments conducted upon him. Deadpool\'s powers and personality traits combine to make a wild, mentally unstable, and unpredictable mercenary. Deadpool has been a member of X-Force and the Thunderbolts, and a self-professed member of the X-Men and the Avengers. The \"Merc with a Mouth\" is infamous for breaking the fourth wall. Created by artist Rob Liefeld and writer Fabian Nicieza, Deadpool made his first appearance in The New Mutants #98 (1991). Rob Liefeld has publicly stated that he had always loved the simplicity of Spider-Man\'s design, and therefore designed a character with a full-head mask. Deadpool was originally a parody of DC Comics\' character Deathstroke, and there are real name similarities (Deathstroke’s real name is Slade Wilson) between the two. Wade\'s alias \"Deadpool\" was taken from the fifth Dirty Harry film The Dead Pool.'),
(23, 'ten', 'RE.png', 'asdf', '', '');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `xmen_heroes`
--
ALTER TABLE `xmen_heroes`
  ADD PRIMARY KEY (`hero_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `xmen_heroes`
--
ALTER TABLE `xmen_heroes`
  MODIFY `hero_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=24;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
